CREATE EXTENSION IF NOT EXISTS pgcrypto;

DROP TABLE IF EXISTS vehicle;

CREATE TABLE vehicle (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    vin TEXT NOT NULL UNIQUE,
    model TEXT NOT NULL,
    year INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);